
###


GET http://localhost:7071/api/HttpTrigger1?query=Donald Trump


###
GET https://llm-azure-hackathon.azurewebsites.net/api/HttpTrigger1?query=Sam Altman
###

###
GET http://localhost:7071/api/ChatAgent?query=give me the steps to fix a KONE elevator buttons 

