
###


GET http://localhost:7071/api/HttpTrigger1?query=Donald Trump

###
GET http://localhost:7071/api/ChatAgent?query=give me the steps to fix a KONE elevator buttons

###
POST http://localhost:7071/api/UploadFiles
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="file"; filename="test.txt"

test
--boundary--    






# ============PRODUCTION============================================================================================================
###
GET https://llm-azure-hackathon.azurewebsites.net/api/HttpTrigger1?query=Sam Altman
###
GET https://llm-azure-hackathon.azurewebsites.net/api/ChatAgent?query=give me the steps to fix a KONE elevator buttons 


