# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - llm-azure-hackathon

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'llm-azure-hackathon'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read #This is required for actions/checkout

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Python version
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{ env.PYTHON_VERSION }}

#       - name: Create and start virtual environment
#         run: |
#           python -m venv venv
#           source venv/bin/activate

#       - name: Install dependencies
#         run: pip install -r requirements.txt
      
#       - name: Zip artifact for deployment
#         run: zip release.zip ./* -r

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: python-app
#           path: |
#             release.zip
#             !venv/
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     permissions:
#       id-token: write #This is required for requesting the JWT
#       contents: read #This is required for actions/checkout

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: python-app

#       - name: Unzip artifact for deployment
#         run: unzip release.zip     
        
#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D38A540F17C34CE1B3B2B9B108C87419 }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_46DB2D901D6449FF946B45C872871C96 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F0DA6B1FEBB4F7198D729C56EFEE825 }}
#       - name: List deployed files
#         run: ls -R
#       - name: 'Deploy to Azure Functions'
#         uses: Azure/functions-action@v1
#         id: deploy-to-function
#         with:
#           app-name: 'llm-azure-hackathon'
#           slot-name: 'Production'
#           package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/release.zip'
#           scm-do-build-during-deployment: true
#           enable-oryx-build: true
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D38A540F17C34CE1B3B2B9B108C87419 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_46DB2D901D6449FF946B45C872871C96 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F0DA6B1FEBB4F7198D729C56EFEE825 }}
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
          
